THEMES = [
  'Shred',
  'Greatest lyrics',
  'Funniest',
  'Cross-Genre Covers',
  '60s',
  'Hair Metal Power Ballad',
  'Water',
  'Time',
  'Describe Your Opponent',
  'Describe Your Moderator',
  'Get The Party Started',
  'Girl’s Names',
  'Instrumentals',
  'British',
  'B-Sides',
  'Prince',
  'Sexytime',
  'Dead Singers',
  '& Bands',
  '“The” Artists',
  'Beach Party',
  'Not English Lyrics',
  'Colors',
  'Forgotten 90s Gems',
  'Songs From Movies',
  'Club Bangers',
  'Hipster Dance Party',
  'Acoustic',
  'Days of The Week',
  'How Do You Feel Right Now?',
  'Mashups',
  'Play Something Banned (From ICA)',
  'Sex, Drugs, And/Or Rock ‘N Roll',
  '1994',
  'The Greatest Song Ever Written',
  'Yacht Rock'
]
